---
title: "senior_edition_data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#read in the data, clean names and select rows that contain human respondents (marked as "finished")
senior_survey_data <- read.csv("senior_survey_data.csv")%>%
  clean_names()%>%
  filter(finished == "True")

#create a df for the first graphic
exceeding_expectations<-senior_survey_data%>%
#group by the question
  group_by(q7)%>%
#count the number of responses for the questions
  summarise(compared_with_expectations = n())
#add in a column with a fixed value (number of respondents)
exceeding_expectations<-add_column(exceeding_expectations, total_number_respondants=68)%>%
#take percents
  mutate(percent_with_this_answer = ((compared_with_expectations/total_number_respondants)*100))

#create a df for the second graphic
positive_or_negative<-senior_survey_data%>%
#group by the question
  group_by(q8)%>%
#count the number of responses for the questions
  summarise(answers = n())
#add in a column with a fixed value (number of respondents)
positive_or_negative<-add_column(positive_or_negative, total_number_respondants=68)%>%
#take percents
  mutate(percent_with_this_answer = ((answers/total_number_respondants)*100))

```
